export const USER_RECOMMENDATIONS_REQUEST = 'USER_RECOMMENDATIONS_REQUEST'
export const USER_RECOMMENDATIONS_SUCCESS = 'USER_RECOMMENDATIONS_SUCCESS'
export const USER_RECOMMENDATIONS_ERROR = 'USER_RECOMMENDATIONS_ERROR'